config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'show'	=> 'users#show'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  resources :books
  

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 100 } 
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
  length: { maximum: 3100 }, uniqueness: {case_sensitive: false} 


  validates :password, presence: true, length: { minimum: 6 }

  
  has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper

end

app/controllers/books_controller.rb
class BooksController < ApplicationController


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		redirect_to user_url(user)
      log_in(user)
  	else
  	
  	flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
  	render 'new'
  	end

  end

  def destroy
  	
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  
  @user = User.find(params[:id])
  
  end


  def create
    @user = User.new(user_params)
    if @user.save
    	flash[:success] = "Welcome to the Sample App!"
    	redirect_to user_url(@user)
      #controller:'static_pages', action: 'help'
      # Handle a successful save.
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/books/index.html.erb
<h1>Siemka ziomki to są The Books.</h1>

<% @user.each do |u| %>
	<p><%= u.name %></p>
	<p><%= u.email %></p>

<%end%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Sample App Biatch!</a>
    by <a href="http://www.michaelhartl.com/">Alex Nowak with Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_schim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
  <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
<%= render 'layouts/schim' %>

</head>
<body>
<%= debug(params) if Rails.env.development? %>
<%= render 'layouts/header' %>
	

    <div class="container">
      <%= yield %>
    </div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>


<center>
	<h1>Welcome to about site. There is no <u style ="color:red; font-size:50px">About</u> in here</h1>
	<p style = 'color: grey'>To jest pierwszy paragraf.</p>
	<p style = 'color: blue'>To jest drugi paragraf.</p>
	<p></p>
</center>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center jumbotron">
  <h1>Contact Us</h1>

  <h2 class = "test">
    Contact us wery quickly via this link: 
    <a href="http://www.railstutorial.org/">#whereisthebeef?</a>
    Biatch!
  </h2>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2 class = "test">
    This is sample app project
    <a href="http://www.railstutorial.org/">#whereisthebeef?</a>
    Biatch!
  </h2>

<hr>
<%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
  <hr>
  <h6>I used bootstrap to this shit!</h6>
  <h6>And I am proud of it!</h6>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
        <%= print user_url(@user) %>
      </h1>
    </section>
  </aside>
</div>